continuous trait values:
{'Abylopsis_eschscholtzi_translation': 517,
 'Aequorea_coerulescens_AY151052_translation': 610,
 'Anthoathecata_translation': 571,
 'Heteractis_crispa_AF420592_translation': 500,
 'Obelia_1_translation': 499,
 'Obelia_2_translation': 515,
 '_Amacrodac': 496,
 '_Avictoria': 508,
 '_Clavula': 483,
 '_Rflo': 574,
 '_alajGFP1': 517,
 '_alajGFP2': 517,
 '_alajGFP3': 504,
 '_amajCyFP': 486,
 '_asulCP': 610,
 '_asulGFP': 499,
 '_ccalGFP3': 517,
 '_ccalOFP1': 561,
 '_ccalRFP1': 598,
 '_ccalRFP2': 587,
 '_ccalYFP1': 523,
 '_ceriOFP': 565,
 '_clytiaGFP': 500,
 '_dendRFP': 506,
 '_dis2RFP': 593,
 '_discRFP': 583,
 '_dstrCyFP': 484,
 '_equaRFP': 611,
 '_gtenCP': 610,
 '_lhemRFP': 581,
 '_mcavCyFP': 474,
 '_mcavGFP2': 515,
 '_mcavRFP': 580,
 '_ptilGFP': 508,
 '_rfloGFP': 518,
 '_rfloRFP': 574,
 '_rmueGFP': 506,
 '_rrenGFP': 508,
 '_scubGFP1': 506,
 '_scubRFP1': 576,
 '_tgeoRFP': 582,
 '_zoanGFP': 506,
 '_zoanRFP': 576,
 '_zoanYFP': 538,
 'amphGFP': 524,
 'anm1GFP1': 495,
 'anm1GFP2': 504,
 'anm2CP': 610,
 'dfGFP': 524,
 'equaOFP': 578,
 'laesGFP': 502,
 'lanYFP': 524,
 'montCP': 610,
 'pdae1GFP': 502,
 'phiYFP': 537,
 'pmeaGFP1': 502,
 'pmeaGFP2': 502,
 'ppluGFP1': 502,
 'ppluGFP2': 502,
 'pporGFP': 507,
 'pporRFP': 595,
 'vecoOFP': 561}
~~~ convergent scenario 1/3 ~~~
trait cutoff = 478.0
2019-01-15 20:39:01,840 - INFO - alignment: example/FPs_data/seq/FPs_62genes_MAFFT.fasta
2019-01-15 20:39:01,896 - INFO - Alphabet usage:
-(76.32%), A(1.01%), C(0.42%), E(1.52%), D(1.28%), G(2.24%), F(1.38%), I(1.21%), H(0.85%), K(1.83%), M(0.85%), L(1.47%), N(1.02%), Q(0.74%), P(1.20%), S(1.30%), R(0.82%), T(1.58%), W(0.20%), V(1.60%), Y(1.13%), X(0.04%) 
2019-01-15 20:39:01,896 - INFO - alignment ok after checking
2019-01-15 20:39:01,897 - INFO - tree: example/FPs_data/tree/RAxML_bipartitions.FPs_62genes_MAFFT-gblocks-raxML-ultram.tree
2019-01-15 20:39:01,921 - INFO - tree ok after checking
2019-01-15 20:39:01,922 - INFO - Sequence and leaf names match.
2019-01-15 20:40:04,140 - INFO - PCOC model: # filtered position: 5/1026
2019-01-15 20:40:04,166 - INFO - PC model: # filtered position: 2/1026
2019-01-15 20:40:04,190 - INFO - OC model: # filtered position: 0/1026
2019-01-15 20:40:04,214 - INFO - UNION model: # filtered position: 5/1026
2019-01-15 20:40:05,515 - INFO - --- 63.7153520584 seconds ---
2019-01-15 20:40:05,515 - INFO - Output dir: example/results/scenarios/478_0/RUN_20190115_203901/
~~~ convergent scenario 2/3 ~~~
trait cutoff = 490.0
Traceback (most recent call last):
  File "/usr/local/bin/pcoc_det.py", line 40, in <module>
    import pandas as pd
  File "/usr/lib/python2.7/dist-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/usr/lib/python2.7/dist-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/usr/lib/python2.7/dist-packages/pandas/core/groupby.py", line 40, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 72, in <module>
    from pandas.core.series import Series
  File "/usr/lib/python2.7/dist-packages/pandas/core/series.py", line 2974, in <module>
    import pandas.tools.plotting as _gfx  # noqa
  File "/usr/lib/python2.7/dist-packages/pandas/tools/plotting.py", line 34, in <module>
    import pandas.tseries.converter as conv
  File "/usr/lib/python2.7/dist-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1162, in <module>
    rcParams = rc_params()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 996, in rc_params
    fname = matplotlib_fname()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 840, in matplotlib_fname
    for fname in gen_candidates():
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 829, in gen_candidates
    yield os.path.join(six.moves.getcwd(), 'matplotlibrc')
OSError: [Errno 2] No such file or directory
~~~ convergent scenario 3/3 ~~~
trait cutoff = 511.0
Traceback (most recent call last):
  File "/usr/local/bin/pcoc_det.py", line 40, in <module>
    import pandas as pd
  File "/usr/lib/python2.7/dist-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/usr/lib/python2.7/dist-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/usr/lib/python2.7/dist-packages/pandas/core/groupby.py", line 40, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 72, in <module>
    from pandas.core.series import Series
  File "/usr/lib/python2.7/dist-packages/pandas/core/series.py", line 2974, in <module>
    import pandas.tools.plotting as _gfx  # noqa
  File "/usr/lib/python2.7/dist-packages/pandas/tools/plotting.py", line 34, in <module>
    import pandas.tseries.converter as conv
  File "/usr/lib/python2.7/dist-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1162, in <module>
    rcParams = rc_params()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 996, in rc_params
    fname = matplotlib_fname()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 840, in matplotlib_fname
    for fname in gen_candidates():
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 829, in gen_candidates
    yield os.path.join(six.moves.getcwd(), 'matplotlibrc')
OSError: [Errno 2] No such file or directory
